### ISSUE TITLE
Require default template publish prior to post.

### ISSUE THREAD

**Issue by jlpell** [badcodeltd/safecms#15]
This is minor but it might be a little more intuitive and self-explanatory if you have a popup that recommends the user should publish a template prior to making their first post.

**Comment by BadCodeShane** [comment]
Absolutely correct, since at the moment the template throws a 404 in the developer console in production. I think the best thing to do is prompt people to do that upon domain or service creation.

**Comment by jlpell** [comment]
> I think the best thing to do is prompt people to do that upon domain or service creation.

Yes, that's even better.

**Comment by BadCodeShane** [comment]
This is resolved in the following commits:

https://github.com/badcodeltd/safecms/commit/64471993555cac71ee0f534e91fc322928f0a99b
https://github.com/badcodeltd/safecms/commit/77dbbce8ff19fd776b1f24cd87602aca6aade06b

In addition, to alleviate confusion, the default post status is now draft instead of published, since published is untrue. This will be released in version 0.0.4.

**Comment by BadCodeShane** [comment]
Version 0.0.4 is now live, closing this issue.
